<script type="text/javascript" src="{{asset('user/js/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/swiper-bundle.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/carousel.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/plugin.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/jquery.nice-select.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/rangle-slider.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/countto.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/shortcodes.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/animation_heading.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/lazysize.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('user/js/main.js')}}"></script>
